name: 'Create confluence release notes'
description: 'Do release note actions in confluence and jira'
inputs:
  RELEASE_TAG:
    required: false
    description: "The tag we are marking as released in jira"
  EXECUTE_RELEASE_NOTES_LAMBDA_ROLE:
    required: true
    description: "The role to assume to execute the release notes lambda"
  DRY_RUN:
    required: false
    description: "whether to use a dry run and do not connect to anything"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: connect to dev account
      if: inputs.DRY_RUN != 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: ${{ inputs.EXECUTE_RELEASE_NOTES_LAMBDA_ROLE }}
        role-session-name: github-actions
    - name: create markJiraReleased payload
      shell: bash
      run: |
        # call mark jira released
        echo "calling mark jira released"
        cat <<EOF > payload.json
        { 
            "releaseVersion": "AWS-account-resources-${{ inputs.RELEASE_TAG }}"
        }
        EOF
        cat payload.json
        if [ "${{ inputs.DRY_RUN}}" != "true" ]; then
          aws lambda invoke --function-name MarkJiraReleased \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json out.txt
        fi
