name: pr

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml

  get_issue_number:
    runs-on: ubuntu-latest
    needs: quality_checks
    outputs:
        issue_number: ${{steps.get_issue_number.outputs.result}}
    steps:
      - uses: actions/github-script@v6
        name: get issue number
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

  list_ci_resources_cf_changes:
    needs: get_issue_number
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: dev-ci
      version: pr-${{github.event.number}}
      change_set_version: pr-${{github.event.number}}
      stack_name: ci-resources
      template: ./cloudformation/ci_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: false
    secrets:
      cf_deploy_role: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  list_account_resources_cf_changes:
    needs: get_issue_number
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: dev-account
      version: pr-${{github.event.number}}
      change_set_version: pr-${{github.event.number}}
      stack_name: account-resources
      template: ./cloudformation/account_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: false
    secrets:
      cf_deploy_role: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
      
